### PR TITLE
Add Pull Request Link to Issue

### PR DESCRIPTION
**Pull request by saadmk11**
closes https://github.com/python/bedevere/issues/501

### CODE REVIEW

**Review by ezio-melotti — COMMENTED** [review]
Does this handle issues with multiple PRs?

**Comment by saadmk11** [comment]
> Does this handle issues with multiple PRs?

If you mean multiple PR's pointing to the same issue, then the answer is yes. :)

**Comment by saadmk11** [comment]
> I really like the way this feature is working! Thanks @saadmk11!
> 
> See [python/cpython#98852](https://github.com/python/cpython/issues/98852) for a nice example of it in action

Always happy to contribute. This was my first contribution to `bedevere` repository. Would be happy to contribute to some more interesting features. :)

**Comment by ezio-melotti** [comment]
> I really like the way this feature is working! Thanks @saadmk11!

Indeed, thanks for the PR!

There are more possible enhancement that could be added in future PRs.  One would be adding the issue to the same list, instead of adding a new one-element list for each PR.  Another option is to add them to a checklist or (even better) to a tasklist.
@saadmk11, would you be interested in expanding this feature?  If not, I can open a separate issue as a reminder.

**Pull request merged**
