### PR TITLE
Fix two typos

### PR DESCRIPTION
**Pull request by delirious-lettuce**
old | new
--- | ---
  `relevent` | `relevant`
  `unlabled` | `unlabeled`

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

**Comment by brettcannon** [comment]
Thanks for the PR, @delirious-lettuce . I've ignored the CLA since this is a trivial change, but do please consider signing it to make any future contribution you make easier to work with.

**Comment by delirious-lettuce** [comment]
@brettcannon ,

Sorry about that. When I asked before I think they said that after signing the CLA my real name would then be published and I was a bit hesitant because of that. I kind of enjoy a bit of pseudo-anonymity on GitHub!

I'm learning about `asyncio` in Python and came across this project by accident. Your code is really clean and I'm enjoying trying to put all the pieces together in my mind.

Again, sorry about the CLA and thanks for your time!

**Comment by delirious-lettuce** [comment]
@brettcannon ,

Maybe you are right, I will have to take another look. I just didn't want to be disrespectful to the PSF by signing up with a fake name (I love Python!), maybe I'll just use my initials?

> But I do understand wanting to stay anonymous, so no worries as long your PRs are all trivial.

Ok, I will remember to keep it simple. Also, I have learned my lesson from that PR you closed a few months ago (on another repo), no more PEP8 style fixes from me!

PS - just wanted to say I have enjoyed watching your Python talks on Youtube

Thanks again!

**Comment by delirious-lettuce** [comment]
If I remember correctly, I think this might have been the list that freaked me out a bit.

https://bugs.python.org/user?@sort=username

**Comment by brettcannon** [comment]
Ah, in that instance you can probably put in initials or a pseudonym for your "real name". As you can see, someone used the name "Nobody/Anonymous" so we don't exactly police that field. 😉

**Comment by brettcannon** [comment]
But seriously, don't feel pressured to sign the CLA if you aren't comfortable.

**Comment by terryjreedy** [comment]
I believe real names are needed for the CLA itself, which is kept in the office.  For the bpo account, a few people have used things like Tom or Steve, which is handier for addressing people in messages than Anonymous or 22.

**Comment by delirious-lettuce** [comment]
@brettcannon & @terryjreedy ,

Ok, thanks for the info guys! I don't have an issue with the PSF having my name privately, it's just the public list I'm not a fan of.

**Pull request merged**
