### PR TITLE
Remove autolink to bpo ticket.

### PR DESCRIPTION
**Pull request by Mariatta**
We get autolinking for free now.

Closes https://github.com/python/core-workflow/issues/361

### CODE REVIEW

**Comment by brettcannon** [comment]
@Mariatta in case you didn't see the test failures.

**Comment by methane** [comment]
https://github.com/python/bedevere/blob/363b02ef402545c8f71fe61a630b3c50c33eb504/bedevere/bpo.py#L15-L17

This can be `Ref: bpo-{issue_number}` too.
It will make auto merged commit message less ugly.

**Comment by nightlark** [comment]
If it helps wrap up this PR (it looks like the GitHub autolinking feature works but the bot is still rewriting `bpo-` refs in commits), here are two patches that I think address the review comments:
* Remove outdated tests: https://github.com/nightlark/bedevere/commit/940e66c120f85034ca8b35fee22989348a496b94.patch
* Use `Ref: bpo-{issue#}` instead of url: https://github.com/nightlark/bedevere/commit/e6c6d5a3bac299f87ef441cbb0665b3f454bacf9.patch

**Comment by arhadthedev** [comment]
Is there any blocker? This PR is stuck for two years.

**Comment by ambv** [comment]
This is outdated now.

**Comment by CAM-Gerlach** [comment]
@brettcannon @Mariatta Could this upstream branch be moved or removed now, to avoid partially blocking full implementation of python/workflow#460 on this repo?

**Comment by Mariatta** [comment]
Since this is outdated we don't need to keep it around, so I'll delete it. Thanks.

**Pull request closed without merging**
