### PR TITLE
Close PRs that try to merge a user's maintenance branch into master

### PR DESCRIPTION
**Pull request by Mariatta**
Close PR that tries to merge the user's maintenance branch into CPython's master.

This will close PR like https://github.com/python/cpython/pull/4266.

### CODE REVIEW

**Comment by brettcannon** [comment]
Obviously keep a close eye on this one once you merge to make sure it doesn't over-reach.

**Comment by Mariatta** [comment]
Thanks!

**Comment by Mariatta** [comment]
Sorry!! I broke things, as seen in python/cpython#4409 🙇‍♀️  Will write another test case and a PR soon.

**Comment by brettcannon** [comment]
I had a feeling that regex might be too permissive. 😄  It's okay, I've just gone ahead and rolled back on Heroku to the last version so there's no rush.

**Pull request merged**
