### PR TITLE
Don't allow failure anymore in 3.8-dev

### PR DESCRIPTION
**Pull request by Mariatta**

### CODE REVIEW

**Comment by Mariatta** [comment]
The asynctest library is not compatible in Python 3.8. It was recently added in #159 by @lysnikolaou 
Is there any workaround for it? Can we make do without asynctest?

**Comment by lysnikolaou** [comment]
@Mariatta the asynctest library provides mocks for async functions. We could use the newly added `AsyncMock`, but we would need to update to 3.8 immediately for that.

**Comment by Mariatta** [comment]
ok thanks for the info. Hmm there is not yet 3.8 Python environment in Heroku, so we can't do it 😟

**Comment by Mariatta** [comment]
Seems like Python 3.8.0 is now available in Heroku. Think we can upgrade?

**Comment by lysnikolaou** [comment]
I'm not sure, what would be best to do. In case @brettcannon says we should upgrade, I could go ahead and push a PR to remove the `asynctest` dependency and update all the relevant tests.

**Comment by brettcannon** [comment]
I always say you should dogfood what you produce, and since this is for Python then we should use Python 3.8 if it's available.

**Comment by lysnikolaou** [comment]
It seems like there is a problem with `aiohttp` as well. After I removed the `asynctest` dependency, I get `DeprecationWarning`s due to `aiohttp` calling `asyncio.shield()` with the loop argument which is deprecated as of 3.8.

Running `pytest -p no:warnings` is ok, which shows that `asynctest` can be removed without a problem.

**Comment by lysnikolaou** [comment]
Opened #211 for this, which fails on Travis with 3.7, but does not with 3.8-dev.

**Comment by Mariatta** [comment]
Superseded by https://github.com/python/bedevere/pull/309

**Pull request closed without merging**
